summary: XML-based font configuration tools
webpage: https://wiki.freedesktop.org/www/Software/fontconfig
version: 2.15.0
bin-url: https://github.com/leleliu008/uppm-package-repository-android-27-aarch64/releases/download/2025.01.25/fontconfig-2.15.0-android-27-arm64-v8a.release.tar.xz
bin-sha: d468082177dc2c8402eb69bbb828ea0e199e9babac649ce5a68e37ffeb33b9af
