summary: XML-based font configuration library
webpage: https://wiki.freedesktop.org/www/Software/fontconfig
version: 2.15.0
bin-url: https://github.com/leleliu008/uppm-package-repository-android-27-aarch64/releases/download/2025.01.25/libfontconfig-2.15.0-android-27-arm64-v8a.release.tar.xz
bin-sha: b4d6b606e65dbc9e35f86b49888469a6952effc2e7e42d4745e39d55a65f3180
