summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-android-27-aarch64/releases/download/2025.01.25/pkg-config-0.29.2-android-27-arm64-v8a.release.tar.xz
bin-sha: 60ac87240f73e4534f3bbb4b4b0090be6f479844a2bbeab75b558d243e5e552d
